# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "natural_time"
gem "color-console"
gem "colorize"
# gem "rails"
